# ==================================================
# FastAPI Traffic Prediction — Kubernetes Service
# ==================================================
apiVersion: v1
kind: Service
metadata:
  name: traffic-api
  namespace: mlops
  labels:
    app: traffic-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: traffic-api
